/**
 * sync-version.mjs
 *
 * Single source of truth for the app version: package.json#version.
 * Regenerates derived artifacts at build time:
 *   - src/app/version.ts  → `export const APP_VERSION = '<version>'`
 *   - src/index.html      → `<title>Tienda-App <version></title>`
 *
 * Idempotent. Node built-ins only (fs, path, url).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
const version = pkg.version;

if (typeof version !== 'string' || version.length === 0) {
  console.error('[sync-version] No version found in package.json');
  process.exit(1);
}

// ── src/app/version.ts ──────────────────────────────────────────────
const versionTsPath = join(root, 'src', 'app', 'version.ts');
const versionTs = [
  '// GENERATED by scripts/sync-version.mjs — DO NOT EDIT MANUALLY.',
  "// Run `npm run sync:version` to regenerate.",
  `export const APP_VERSION = '${version}';`,
  '',
].join('\n');
writeFileSync(versionTsPath, versionTs);

// ── src/index.html <title> ──────────────────────────────────────────
const htmlPath = join(root, 'src', 'index.html');
const html = readFileSync(htmlPath, 'utf8');
const titleRegex = /(<title>Tienda-App )[^<]*(<\/title>)/;
if (!titleRegex.test(html)) {
  console.error(
    '[sync-version] Could not find <title>Tienda-App ...</title> in src/index.html',
  );
  process.exit(1);
}
const updatedHtml = html.replace(
  titleRegex,
  (_match, prefix, suffix) => `${prefix}${version}${suffix}`,
);
writeFileSync(htmlPath, updatedHtml);

console.log(`[sync-version] Synced version artifacts to ${version}`);
